name: FrontendService CI/CD

on:
  push:
    branches: [ "main" ]  # Changed from master to main
    paths:
      - 'frontend-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend-service/**'

env:
  AZURE_CONTAINER_REGISTRY: ocorneracr3
  APP_NAME: frontendservice
  RESOURCE_GROUP: Online-cornerRG
  IMAGE_TAG: ${{ github.sha }}
  DOCKERFILE_PATH: ./frontend-service/Dockerfile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend-service
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.APP_NAME }}:latest
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NODE_ENV=production

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
        resource-group: ${{ env.RESOURCE_GROUP }}
        slot-name: production

    - name: Verify deployment
      run: |
        DEPLOYMENT_STATUS=$(az webapp show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.APP_NAME }} \
          --query "state" -o tsv)
        echo "WebApp status: $DEPLOYMENT_STATUS"
        
        curl -s -o /dev/null -w "%{http_code}" https://${{ env.APP_NAME }}.azurewebsites.net | grep -q 200